version: "3"

services:
  datomic:
    container_name: datomic
    build:
      context: datomic
    restart: always
    ports:
      - "4334:4334"
      - "4335:4335"
      - "4336:4336"

  zookeeper:
    container_name: zookeeper
    build:
      context: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    build:
      context: kafka
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
