FROM sapmachine:17-jdk-ubuntu

ENV KAFKA_VERSION "3.6.0"
ENV SCALA_VERSION "2.13"

RUN apt-get update && apt-get install -y wget
RUN mkdir /kafka
WORKDIR kafka
RUN wget \
    -O kafka-binaries.tgz \
    https://downloads.apache.org/kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz \
    && tar -xvzf kafka-binaries.tgz --strip 1 \
    && rm kafka-binaries.tgz

COPY ./start-zookeeper.sh  /kafka

CMD ["sh", "/kafka/start-zookeeper.sh"]    
