FROM sapmachine:17-jdk-ubuntu
ENV DATOMIC_VERSION "1.0.7021"

RUN apt-get update && apt-get install -y unzip wget
RUN wget \
    -O /datomic-pro.zip \ 
    https://datomic-pro-downloads.s3.amazonaws.com/${DATOMIC_VERSION}/datomic-pro-${DATOMIC_VERSION}.zip \
    && unzip datomic-pro.zip \
    && rm /datomic-pro.zip \
    && mv /datomic-pro-${DATOMIC_VERSION} /datomic

COPY ./dev-mode.properties /datomic/config
WORKDIR /datomic

ENTRYPOINT ["./bin/transactor", "config/dev-mode.properties"]
EXPOSE 4334 4335 4336
